# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Informativo Integração
email: integracao@yapay.com.br
description: > # this means to ignore newlines until "baseurl:"
  Informativo Integração Yapay
url: ""
baseurl: "https://yapaypagamentos.github.io/info-integracao"



# Build settings
markdown: kramdown
exclude: ["README.md"]
excerpt_separator: "<!-- more -->"

permalink: none

authors:
  ana_nava:
    name: Ana Nava Bagagi
    email: ana.nava@yapay.com.br
    image: "/images/ana_nava.jpg"
    bio: Analista de Integração
